const sessionMarkdownGenerator = require('./markdownGenerator');
const encounterMarkdownGenerator = require('./encounterMarkdownGenerator');

function pad(n) {
  return String(n).padStart(3, '0');
}

function safe(str) {
  return String(str == null ? '' : str).trim();
}

function packetFilename(session) {
  return `session-${pad(session.sessionNumber || 0)}-packet`;
}

function buildPacketMarkdown({ session, linkedNpcs = [], linkedEncounters = [] }) {
  const sessionMarkdown = session.markdown || sessionMarkdownGenerator.generate(session.data || {});
  const lines = [];
  const sessionNumber = pad(session.sessionNumber || session.data?.sessionNumber || 0);

  lines.push(`# Session Packet — Session ${sessionNumber}`);
  lines.push('');
  lines.push(`**Session ID:** ${safe(session.id)}`);
  if (session.date || session.data?.date) lines.push(`**Date:** ${safe(session.date || session.data?.date)}`);
  if (session.partyLevel || session.data?.partyLevel) lines.push(`**Party Level:** ${safe(session.partyLevel || session.data?.partyLevel)}`);
  if (linkedNpcs.length) lines.push(`**Linked NPCs:** ${linkedNpcs.length}`);
  if (linkedEncounters.length) lines.push(`**Linked Encounter Plans:** ${linkedEncounters.length}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  lines.push('## Session Plan');
  lines.push('');
  lines.push(sessionMarkdown.trim());
  lines.push('');

  if (linkedNpcs.length) {
    lines.push('---');
    lines.push('');
    lines.push('## Linked NPCs');
    lines.push('');
    linkedNpcs.forEach(npc => {
      const nickname = npc.nickname ? ` "${safe(npc.nickname)}"` : '';
      lines.push(`- **${safe(npc.name)}**${nickname} (${safe(npc.id)})${npc.exists ? '' : ' [missing]'}`);
    });
    lines.push('');
  }

  if (linkedEncounters.length) {
    lines.push('---');
    lines.push('');
    lines.push('## Linked Encounter Plans');
    lines.push('');
    linkedEncounters.forEach((encounter, index) => {
      lines.push(`### ${safe(encounter.name || encounter.id)}`);
      lines.push('');
      if (encounter.markdown) {
        lines.push(encounter.markdown.trim());
      }
      if (index < linkedEncounters.length - 1) {
        lines.push('');
        lines.push('---');
        lines.push('');
      } else {
        lines.push('');
      }
    });
  }

  lines.push('---');
  lines.push('');
  lines.push(`*Generated by D&D Session Master on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}*`);

  return lines.join('\n');
}

function buildPacketHtml(context) {
  const template = require('../templates/sessionPacketPdfTemplate');
  return template.render(context);
}

module.exports = {
  packetFilename,
  buildPacketMarkdown,
  buildPacketHtml,
};
